name: Linux CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Compile
      run: gcc -o mogger mogger_linux.c

    - name: Run tests
      run: |
        ./mogger &
        PID=$!
        sleep 5
        kill $PID

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: mogger-linux
        path: mogger
